before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - 
    env:
    - CGO_ENABLED=0
    ldflags:
      - -s -w -X "github.com/atredispartners/flamingo/cmd.Version={{.Version}}"  
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:         
      - goos: darwin
        goarch: arm     
      - goos: freebsd
        goarch: arm
signs:
  - id: default
    cmd: gpg
    args:
      - -u x@hdm.io
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: checksum      
archives:
- replacements:
    darwin: macos
    386: x86
    arm64: aarch64
  format: binary
  files:
    - none*
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{.Arm}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
